#!/bin/bash

# Backup existing Zsh files
echo "Backing up existing Zsh files..."
backup_file() {
    if [ -f "$1" ]; then
        cp "$1" "$1.bak.$(date +%Y%m%d_%H%M%S)"
        echo "Backed up $1"
    fi
}

backup_file ~/.zshrc
backup_file ~/.zprofile
backup_file ~/.zsh_aliases

# Create new Zsh configuration files
echo "Creating new Zsh configuration files..."

# Create .zsh_aliases if it doesn't exist
if [ ! -f ~/.zsh_aliases ]; then
    if [ -f ~/.bash_aliases ]; then
        echo "Converting bash_aliases to zsh_aliases..."
        cp ~/.bash_aliases ~/.zsh_aliases
    else
        echo "Creating new zsh_aliases..."
        touch ~/.zsh_aliases
    fi
fi

# Initialize new .zshrc
cat > ~/.zshrc << 'EOL'
# Generated by bash-to-zsh migration script
# Sourcing order: zshenv -> zprofile -> zshrc -> zlogin

# Load aliases
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# Zsh-specific settings
setopt AUTO_CD              # If command is a directory path, cd into it
setopt NO_CASE_GLOB        # Case insensitive globbing
setopt NUMERIC_GLOB_SORT   # Sort filenames numerically when relevant
setopt EXTENDED_GLOB       # Extended globbing capabilities

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
EOL

# Transfer relevant non-Bash-specific content from .bashrc
if [ -f ~/.bashrc ]; then
    echo "Analyzing .bashrc for compatible configurations..."
    # Extract environment variables
    grep "^export" ~/.bashrc >> ~/.zshrc
    # Extract functions (excluding those with Bash-specific syntax)
    awk '/^[a-zA-Z_-]+\(\).*{/,/^}/ { print }' ~/.bashrc >> ~/.zshrc
fi

# Transfer relevant content from .bash_profile to .zprofile
if [ -f ~/.bash_profile ]; then
    echo "Creating .zprofile from .bash_profile..."
    # Extract PATH and environment variables
    grep "^export" ~/.bash_profile > ~/.zprofile
    # Extract non-Bash-specific evaluations
    grep "^eval" ~/.bash_profile | grep -v "bash" >> ~/.zprofile
fi

# Add common source commands
cat >> ~/.zshrc << 'EOL'

# Load Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Initialize pyenv if installed
if command -v pyenv >/dev/null; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
fi

# Load starship prompt if installed
if command -v starship >/dev/null; then
    eval "$(starship init zsh)"
fi

# Source additional configurations
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
[ -f "$HOME/.deno/env" ] && source "$HOME/.deno/env"
[ -f ~/.secrets ] && source ~/.secrets
EOL

echo "Migration complete! New Zsh configuration files have been created."

# Offer to switch to Zsh if not already the default
if [ "$SHELL" != "/bin/zsh" ]; then
    echo "Your current shell is $SHELL. Would you like to switch to Zsh? (y/n)"
    read -r SWITCH_TO_ZSH
    if [ "$SWITCH_TO_ZSH" = "y" ]; then
        echo "Changing default shell to Zsh..."
        chsh -s /bin/zsh
        echo "Default shell changed to Zsh. Please restart your terminal."
    else
        echo "Default shell not changed."
    fi
fi

echo "Done! Please restart your terminal for changes to take effect."

