# Minimal white-on-black starship config with clear separation
format = "$directory$git_branch$git_status$line_break$character"

[directory]
style = "fg:white"
format = "[$path]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
style = "fg:bright-white"
format = " on [$symbol$branch]($style)"

[git_status]
style = "fg:white"
format = " ·[$all_status$ahead_behind]($style)"
conflicted = " conflict"
ahead = " ↑${count}"
behind = " ↓${count}"
diverged = " ↕${ahead_count}/${behind_count}"
untracked = " +${count}"
stashed = " stash"
modified = " ~${count}"
staged = " staged"
renamed = " renamed"
deleted = " -${count}"

[character]
success_symbol = "[>](fg:white)"
error_symbol = "[>](fg:bright-red)"

# Disable modules that add clutter
[aws]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
