# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 8

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# Remove gaps and border when a workspace has a single tiled window.
workspace = w[t1] s[false], gapsout:0, gapsin:0, bordersize:0, rounding:false
workspace = w[tg1] s[false], gapsout:0, gapsin:0, bordersize:0, rounding:false
workspace = f[1] s[false], gapsout:0, gapsin:0, bordersize:0, rounding:false

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

render {
    direct_scanout = 1
  }
