#add_newline = true

# A simpler format: directory followed by a character
format = "$directory $character "

[directory]
# Just a foreground color—no background—so it doesn't look blocky
style = "fg:#7aa2f7"  # A nice Tokyonight blue
format = "$path"
truncation_length = 3
truncation_symbol = "…/"

# Remove backgrounds and complex formatting from Git too, at least initially
[git_branch]
symbol = " "
style = "fg:#7aa2f7"
format = "$symbol$branch"
disabled = true  # Disable for now; re-enable later once you like the look

[git_status]
disabled = true  # Same as above, keep it simple at first

[character]
success_symbol = "➜"
error_symbol = "➜"
