# Managed by chezmoi - https://github.com/btuckerc/boilerplate
# Global mise configuration - project-specific overrides go in project mise.toml files

[tools]
# Language Runtimes
node = "lts"
python = "3.13"
go = "1.25"
ruby = "3"

# Core Tools
"aqua:neovim/neovim" = "latest"
"aqua:cli/cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"asdf:mise-plugins/mise-tmux" = "latest"
claude = "latest"
"aqua:sst/opencode" = "latest"

# Shell & Navigation
"ubi:twpayne/chezmoi" = "latest"
"ubi:starship/starship" = "latest"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:junegunn/fzf" = "latest"

# CLI Utilities
"ubi:sharkdp/bat" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:sxyazi/yazi" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:charmbracelet/gum" = "latest"
"ubi:jesseduffield/lazygit" = "latest"
"ubi:tree-sitter/tree-sitter" = "latest"
"ubi:carapace-sh/carapace-bin" = { version = "latest", exe = "carapace" }

# Language Servers
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:hashicorp/terraform-ls" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:pyright" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"gem:solargraph" = "latest"

# Formatters
"npm:prettier" = "latest"
"pipx:black" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:mvdan/gofumpt" = "latest"
"aqua:mvdan/sh" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

# Additional Tools
"npm:@playwright/mcp" = "latest"
"gem:rails" = "latest"

# External dependencies (install via homebrew/package manager):
# - git, eza, btop

[settings]
experimental = true
legacy_version_file = true
always_keep_download = false
plugin_autoupdate_last_check_duration = "7d"
jobs = 4
verbose = false
asdf_compat = true
color = true
task_output = "prefix"

[settings.pipx]
uvx = true

[settings.npm]
bun = true
