[tools]
# Core dependencies - must install first
python = "3.13"
uv = "latest"
node = "lts"
go = "1.25"

# CLI tools (fast binary downloads)
"ubi:twpayne/chezmoi" = "latest"
"ubi:starship/starship" = "latest"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:sxyazi/yazi" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:charmbracelet/gum" = "latest"
"ubi:jesseduffield/lazygit" = "latest"
"ubi:tree-sitter/tree-sitter" = "latest"
"ubi:carapace-sh/carapace-bin" = { version = "latest", exe = "carapace" }

# Editor and dev tools
"aqua:neovim/neovim" = "latest"
"aqua:cli/cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"asdf:mise-plugins/mise-tmux" = "latest"

# Language servers (require node/python/go)
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:pyright" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:prettier" = "latest"
"npm:@playwright/mcp" = "latest"

"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

"pipx:black" = "latest"
"pipx:yubikey-manager" = "latest"

"aqua:LuaLS/lua-language-server" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:hashicorp/terraform-ls" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:mvdan/gofumpt" = "latest"
"aqua:mvdan/sh" = "latest"

# Ruby tools (install last due to build complexity)
ruby = "3"
"gem:solargraph" = "latest"
"gem:rails" = "latest"

[settings]
experimental = true
legacy_version_file = true
always_keep_download = false
plugin_autoupdate_last_check_duration = "7d"
jobs = 2
verbose = false
asdf_compat = true
color = true
task_output = "prefix"
http_timeout = "120"
raw = false

[hooks]
preinstall = "bash ${XDG_CONFIG_HOME:-$HOME/.config}/mise/hooks/preinstall"

[env]
# Fix Ruby build requiring 'python' command
_.path = [
  "{{ config_root }}/shims",
  "~/.local/share/mise/shims",
]

[env._.python]
# Ensure python command exists for tools that need it


[settings.pipx]
uvx = true

[settings.npm]
bun = true
